from Basis import ControlWindow
from Basis.CaptureWindow import windowsht
from scipy import misc
import time
import math
import datetime

'''Define the Character Fight Commands '''
def characterfight(ws, character):
    if character=="indra":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.5)
        cl.avaliable_press_keyboard(ws,"s", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.5)
    elif character=="fnen":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=1)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        time.sleep(1)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
    elif character=="guanyu":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"r", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"right_arrow", slp=1)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        # time.sleep(1)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character=="fsm":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character=="msm":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"w", slp=0.2)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
    elif character=="xukong":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character=="modao":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character=="yingwu":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"h", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.5)
        # cl.avaliable_press_keyboard(ws,"a", slp=0.5)
        # cl.avaliable_press_keyboard(ws,"s", slp=0.5)
    elif character=="zhaohuan":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"r", slp=0.3)
        cl.avaliable_press_keyboard(ws,"t", slp=0.3)
        cl.avaliable_press_keyboard(ws,"y", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
    elif character=="saint":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"r", slp=0.3)
        cl.avaliable_press_keyboard(ws,"t", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"g", slp=0.3)
    elif character=="seraph":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"g", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
    elif character=="monk":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"h", slp=0.3)
        cl.avaliable_press_keyboard(ws,"y", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.5)
        cl.avaliable_press_keyboard(ws,"s", slp=0.5)
        cl.avaliable_press_keyboard(ws,"d", slp=0.5)
        cl.avaliable_press_keyboard(ws,"f", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.5)
    elif character=="nvdaqiang":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
    elif character == "wunv":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"r", slp=1.0)
    elif character == "palading":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.5)
        # cl.avaliable_press_keyboard(ws,"q", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
    elif character == "jirou":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        # cl.avaliable_press_keyboard(ws,"numpad_6", slp=0.5)
        cl.avaliable_press_keyboard(ws,"q", slp=0.2)
        cl.avaliable_press_keyboard(ws,"a", slp=0.2)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"g", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"r", slp=0.3)
    elif character == "fff":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.2)
        cl.avaliable_press_keyboard(ws,"s", slp=0.2)
        cl.avaliable_press_keyboard(ws,"d", slp=0.2)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
    elif character == "andi":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.2)
        cl.avaliable_press_keyboard(ws,"s", slp=0.2)
        cl.avaliable_press_keyboard(ws,"d", slp=0.2)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character == "hundun":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.2)
        cl.avaliable_press_keyboard(ws,"s", slp=0.2)
        cl.avaliable_press_keyboard(ws,"d", slp=0.2)
        cl.avaliable_press_keyboard(ws,"q", slp=0.2)
        cl.avaliable_press_keyboard(ws,"w", slp=0.2)
        cl.avaliable_press_keyboard(ws,"e", slp=0.2)
        cl.avaliable_press_keyboard(ws,"f", slp=0.2)
    elif character == "hongyan":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.nomal_press_keyboard("z", slp=0.5)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws, "d", slp=0.3)
        cl.avaliable_press_keyboard(ws, "e", slp=0.3)
    elif character == "mudan":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character == "heiqiang":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"y", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
    elif character == "siyi":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
    elif character == "renzhe":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character == "fengfa":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
    elif character == "jixie":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"t", slp=0.3)
    elif character == "mnen":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws,"a", slp=0.3)
        cl.avaliable_press_keyboard(ws,"s", slp=0.3)
        cl.avaliable_press_keyboard(ws,"d", slp=0.3)
        cl.avaliable_press_keyboard(ws,"q", slp=0.3)
        cl.avaliable_press_keyboard(ws,"w", slp=0.3)
        cl.avaliable_press_keyboard(ws,"e", slp=0.3)
        cl.avaliable_press_keyboard(ws,"f", slp=0.3)
    elif character == "guiqi":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws, "a", slp=0.3)
        cl.avaliable_press_keyboard(ws, "s", slp=0.3)
        cl.avaliable_press_keyboard(ws, "d", slp=0.3)
        cl.avaliable_press_keyboard(ws, "q", slp=0.3)
        cl.avaliable_press_keyboard(ws, "w", slp=0.3)
        cl.avaliable_press_keyboard(ws, "e", slp=0.3)
    elif character == "tegong":
        cl = ControlWindow.windowcl()
        cl.move_window(ws._handle, 0, 0)
        cl.nomal_press_keyboard("0", slp=0.3)
        cl.avaliable_press_keyboard(ws, "a", slp=0.3)
        cl.avaliable_press_keyboard(ws, "s", slp=0.3)
        cl.avaliable_press_keyboard(ws, "q", slp=0.3)
        cl.avaliable_press_keyboard(ws, "w", slp=0.3)
